# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 205afd180db25c2a746cb3755bf9aa664d1069d039c94d68b696bf49373706075d3f04c1c4b5c5946c151abd7b5391f197ca1f1b3fcbd476e8958a3b0b66ffa2

test:
  secret_key_base: 5cf606d227ebd528d5e4352e7532fbc03863c2f2f69c88da786f29a3a74fd3ec4d1c118cfcb7ca77c8f5838e8c656e0d74a0e2a65b6cee335bd75a2d885bb49c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
